spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concurrency
    username: root
    password: Jhan00254!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
